sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t knotehow/react-base -f Dockerfile.dev .

script:
  - docker run -e CI=true knotehow/react-base npm run test -- --coverage